# Commands to be performed on player's death
CommandsOnDeath:
  Command1: ""
  Command2: ""

# Base amount for starting lives and maximum lives
Lives:
  MaxLives: 100
  StartingAmount: 10
  Penalty: 1

# Database parameters
Database:
  Database: ""
  URL: ""
  User: ""
  Password: ""

